---

- name: Install dependencies
  apt: pkg=python-pip
  when: ansible_os_family == 'Debian'

- name: Install supervisor
  pip: name=supervisor version={{ supervisor_version }}
  notify:
    - supervisor restart
    
- name: Install superlance
  pip: name=superlance
  when: supervisor_superlance

- name: Prepare directories
  file: state=directory path={{item}}
  with_items:
    - "{{supervisor_cfgdir}}"
    - "{{supervisor_logdir}}"
    - "{{supervisor_incdir}}"

- name: Configure supervisor - pt. 1
  template: src=supervisord.conf.j2 dest={{supervisor_conf_file}} owner=root group=root mode=0644
  notify:
    - supervisor restart

- name: Find systemd information
  command: which systemctl
  ignore_errors: yes
  register: is_systemd

- name: Configure upstart supervisor
  template: src=supervisor_upstart.conf.j2 dest=/etc/init/supervisor.conf owner=root group=root mode=0755
  when: not is_systemd

- name: Configure systemd supervisor
  template: src=supervisor_systemd.conf.j2 dest=/etc/init.d/supervisor owner=root group=root mode=0755
  when: is_systemd

- name: Enable systemd supervisor service
  service: name=supervisor enabled=yes
  when: is_systemd

- name: Ensure the supervisor is started
  service: name=supervisor state=started
